jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Proyecto\PrincipalBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: ProyectoPrincipalBundle:User, property: username }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /control/acceso
                check_path:  /control/login_check
                default_target_path: /
            logout:
              path: /control/logout
              target: /
    access_control:
        - { path: /_wdt/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /_profiler/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/control/acceso, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/control/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/control/cuenta/guardar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/control, roles: ROLE_ADMIN }
