proyecto_front_homepage:
    pattern:  /
    defaults: { _controller: ProyectoFrontBundle:Default:inicio }
proyecto_front_organizacion:
    pattern:  /organizacion
    defaults: { _controller: ProyectoFrontBundle:Default:organizacion }
proyecto_front_organizacion_articulo:
    pattern:  /organizacion/{id}
    defaults: { _controller: ProyectoFrontBundle:Default:articulo,id: '1' }
proyecto_front_informacion:
    pattern:  /informacion
    defaults: { _controller: ProyectoFrontBundle:Default:informacion }
proyecto_front_informacion_articulo:
    pattern:  /informacion/{id}
    defaults: { _controller: ProyectoFrontBundle:Default:articulo,id: '1' }
proyecto_front_descargas:
    pattern:  /descargas
    defaults: { _controller: ProyectoFrontBundle:Default:descargas }
proyecto_front_contacto:
    pattern:  /contacto
    defaults: { _controller: ProyectoFrontBundle:Default:contacto }

